# Generated by Django 5.1.1 on 2024-09-14 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_remove_bus_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.bus'),
        ),
        migrations.AlterField(
            model_name='student',
            name='register_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
